@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        @include('schooladmin.partials.sidebar')

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 py-4">
            <h1 class="h3 mb-4 text-gray-800">School Bank Details Configuration</h1>

           
            <div class="row">
                <div class="col-lg-8">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Payment & Bank Details</h6>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('schooladmin.settings.update') }}" method="POST">
                                @csrf
                                
                                <div class="alert alert-info small mb-4">
                                    <i class="fas fa-info-circle me-1"></i> 
                                    These details will appear on all student invoices generated by your school.
                                </div>

                                <div class="mb-3">
                                    <label class="form-label fw-bold">Bank Name</label>
                                    <input type="text" name="bank_name" class="form-control" 
                                           value="{{ old('bank_name', $school->bank_name) }}" 
                                           placeholder="e.g. First Bank of Nigeria" required>
                                </div>

                                <div class="row">
                                    <div class="col-md-6 mb-3">
                                        <label class="form-label fw-bold">Account Number</label>
                                        <input type="text" name="account_number" class="form-control" 
                                               value="{{ old('account_number', $school->account_number) }}" 
                                               placeholder="e.g. 2005550011" required>
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <label class="form-label fw-bold">Account Name</label>
                                        <input type="text" name="account_name" class="form-control" 
                                               value="{{ old('account_name', $school->account_name) }}" 
                                               placeholder="e.g. Educare High School - Tuition" required>
                                    </div>
                                </div>

                                <hr>
                                <button type="submit" class="btn btn-primary px-4">
                                    Save Changes
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </main>
    </div>
</div>
@endsection